use correct server address. put if statment all on one line

diff --git a/.drone.yml b/.drone.yml
--- a/.drone.yml
+++ b/.drone.yml
@@ -85,18 +85,14 @@ steps:
     image: drone/cli:1.6.2-alpine
     environment:
       DRONE_BUILD_PARENT: ${DRONE_BUILD_PARENT}
-      DRONE_SERVER: https://drone-gl.acp.homeoffice.gov.uk/
+      DRONE_SERVER: https://drone-gh.acp.homeoffice.gov.uk
       DRONE_TOKEN:
         from_secret: drone_token
     commands:
-      - echo 'drone server =' $DRONE_SERVER
       - echo 'parent build =' $DRONE_BUILD_PARENT
       - LAST_BUILD=$(drone build ls --format '{{.Number}}' --branch "task/eahw-2428/manual-promote-to-prod-pipeline" --status success --event push --limit 100 "UKHomeOffice/callisto-timecard-restapi" | head -n 1)
       - echo 'last succesful build = ' $LAST_BUILD
-      - if [ $LAST_BUILD != $DRONE_BUILD_PARENT ]; then
-          echo 'Could not promote as last build was not successful'
-          exit 1
-        fi
+      - if [ $LAST_BUILD != $DRONE_BUILD_PARENT ]; then echo 'Could not promote as last build was not successful'; exit 1; fi
 
 
 ---
